export const PARAGRAPH_LIST_REQUEST = "PARAGRAPH_LIST_REQUEST";
export const PARAGRAPH_LIST_SUCCESS = "PARAGRAPH_LIST_SUCCESS";
export const PARAGRAPH_LIST_FAIL = "PARAGRAPH_LIST_FAIL";

export const PARAGRAPH_DETAILS_REQUEST = "PARAGRAPH_DETAILS_REQUEST";
export const PARAGRAPH_DETAILS_SUCCESS = "PARAGRAPH_DETAILS_SUCCESS";
export const PARAGRAPH_DETAILS_FAIL = "PARAGRAPH_DETAILS_FAIL";
